
#
# Makefile standard rules and default targets
#
# This makefile is supposed to be included by the main
# makefile after the following variables have been set:
#
# OBJDIR   - The directory where all temporary files will be placed.
# CFLAGS   - Options given to the compiler when compiling C files
# CPPFLAGS - Options given to the compiler when compiling C++ files
# OBJFILES - List of object files.
#
# The $(OBJDIR) varaiable will be prepended to all elements in
# the $(OBJS) list and then a new variable named DEPS will be
# initiated with all the elements from $(OBJS) with all ".o" prefixes
# replaced with ".d".


OBJFILES := $(patsubst %.c, %.o, $(SOURCES))
OBJFILES := $(patsubst %.cpp, %.o, $(OBJFILES))
OBJFILES := $(addprefix $(OBJDIR)/,$(OBJFILES))

DEPFILES := $(patsubst %.o, %.d, $(OBJFILES))

TARGET_DIRS := $(OBJDIR) $(addprefix $(OBJDIR)/,$(SUBDIRS))
reverse = $(if $(1),$(call reverse,$(wordlist 2,$(words $(1)),$(1)))) $(firstword $(1))
TARGET_DIRS_REVERSE := $(call reverse,$(TARGET_DIRS))

$(OBJDIR)/%.o : %.c
	@echo Compiling C : $<
	@$(CC) $(CFLAGS) $< -MMD -MP -MF$(patsubst %.o, %.d, $@) -MT"$@" -o $@
$(OBJDIR)/%.o : %.cpp
	@echo Compiling CPP : $<
	@$(CCPP) $(CPPFLAGS) $< -MMD -MP -MF$(patsubst %.o, %.d, $@) -MT"$@" -o $@
$(OBJDIR)/%.o : %.s
	@echo Assambling: $<
	@$(CC) $(AFLAGS) -x assembler-with-cpp $< -o $@
$(OBJDIR)/%.o : %.S
	@echo Assambling: $<
	@$(CC) $(CFLAGS) -x assembler-with-cpp $< -o $@


#$(OBJDIR)/%.d : %.c
#	@echo Making dependencies for : $<
#	@$(CC) $(CFLAGS) -M $< | sed 's%^\(.*\):%$(OBJDIR)\/\1:%' > $@
#$(OBJDIR)/%.d : %.cpp
#	@echo Making dependencies for : $<
#	@$(CC) $(CPPFLAGS) -M $< | sed 's%^\(.*\):%$(OBJDIR)\/\1:%' > $@
#$(OBJDIR)/%.d : %.s
#	@touch $@
#$(OBJDIR)/%.d : %.S
#	@touch $@

