
#pragma once

#include <string>
#include <string_view>

//#include <App/Application.h>
//#include <ApplicationServer/BlitterUtils.h>
//#include <ApplicationServer/Font.h>
#include <ApplicationServer/Protocol.h>
#include <DataTranslation/DataTranslator.h>
#include <DeviceControl/DeviceControlInvoker.h>
//#include <DeviceControl/HID.h>
//#include <DeviceControl/I2C.h>
#include <DeviceControl/MultiMotor.h>
//#include <DeviceControl/SDCARD.h>
//#include <DeviceControl/SPI.h>
//#include <DeviceControl/TLV493D.h>
//#include <DeviceControl/USART.h>
//#include <DeviceControl/WS2812B.h>
//#include <Eigen/Eigen>
#include <GUI/Bitmap.h>
#include <GUI/Color.h>
#include <GUI/Desktop.h>
#include <GUI/Dialogs/DialogBase.h>
#include <GUI/Dialogs/ErrorMessageBox.h>
#include <GUI/Dialogs/MessageBox.h>
#include <GUI/Dialogs/TextInputDialog.h>
#include <GUI/Font.h>
#include <GUI/GUIDefines.h>
#include <GUI/GUIEvent.h>
#include <GUI/KeyboardView.h>
#include <GUI/LayoutNode.h>
#include <GUI/NamedColors.h>
#include <GUI/Region.h>
#include <GUI/StandardColorsDefinition.h>
#include <GUI/View.h>
#include <GUI/ViewFactory.h>
#include <GUI/ViewFactoryContext.h>
#include <GUI/ViewScroller.h>
#include <GUI/Widgets/BitmapView.h>
#include <GUI/Widgets/Button.h>
#include <GUI/Widgets/ButtonBase.h>
#include <GUI/Widgets/ButtonGroup.h>
#include <GUI/Widgets/CheckBox.h>
#include <GUI/Widgets/Checkbox.h>
#include <GUI/Widgets/Control.h>
#include <GUI/Widgets/DropdownMenu.h>
#include <GUI/Widgets/Dropdownmenu.h>
#include <GUI/Widgets/GroupView.h>
#include <GUI/Widgets/IconView.h>
#include <GUI/Widgets/ListView.h>
#include <GUI/Widgets/ListViewRow.h>
#include <GUI/Widgets/ListViewStringRow.h>
#include <GUI/Widgets/MVCBaseView.h>
#include <GUI/Widgets/MVCGridView.h>
#include <GUI/Widgets/MVCListView.h>
#include <GUI/Widgets/Menu.h>
#include <GUI/Widgets/MenuItem.h>
#include <GUI/Widgets/MenuSeparator.h>
#include <GUI/Widgets/ProgressBar.h>
#include <GUI/Widgets/RadioButton.h>
#include <GUI/Widgets/ScrollBar.h>
#include <GUI/Widgets/ScrollView.h>
#include <GUI/Widgets/ScrollableView.h>
#include <GUI/Widgets/Slider.h>
#include <GUI/Widgets/TabView.h>
#include <GUI/Widgets/Tabview.h>
#include <GUI/Widgets/TextBox.h>
#include <GUI/Widgets/TextEditView.h>
#include <GUI/Widgets/TextView.h>
#include <GUI/Window.h>
//#include <Kernel/HAL/DMA.h>
//#include <Kernel/HAL/DigitalPort.h>
//#include <Kernel/HAL/PeripheralMapping.h>
//#include <Kernel/HAL/Peripherals.h>
//#include <Kernel/HAL/STM32/ADC_STM32.h>
//#include <Kernel/HAL/STM32/DMARequestID.h>
//#include <Kernel/HAL/STM32/PinMuxTarget_STM32.h>
//#include <Kernel/HAL/STM32/QSPI_STM32.h>
//#include <Kernel/HAL/STM32/QSPI_STM32_IS25LP512M.h>
//#include <Kernel/HAL/STM32/RealtimeClock.h>
//#include <Kernel/HAL/STM32/ResetAndClockControl.h>
//#include <Kernel/HAL/STM32/SDRAM_STM32.h>
//#include <Kernel/HAL/STM32/USBDevice_STM32.h>
//#include <Kernel/HAL/STM32/USBHost_STM32.h>
//#include <Kernel/HAL/STM32/USB_STM32.h>
//#include <Kernel/IRQDispatcher.h>
//#include <Kernel/KAddressValidation.h>
//#include <Kernel/KConditionVariable.h>
//#include <Kernel/KHandleArray.h>
#include <Kernel/KLogging.h>
//#include <Kernel/KMessagePort.h>
//#include <Kernel/KMutex.h>
//#include <Kernel/KNamedObject.h>
//#include <Kernel/KObjectWaitGroup.h>
//#include <Kernel/KPowerManager.h>
//#include <Kernel/KProcess.h>
//#include <Kernel/KSemaphore.h>
//#include <Kernel/KThread.h>
//#include <Kernel/KThreadCB.h>
//#include <Kernel/KThreadWaitNode.h>
//#include <Kernel/KTime.h>
//#include <Kernel/KWaitableObject.h>
//#include <Kernel/Kernel.h>
//#include <Kernel/Logging/LogManager.h>
//#include <Kernel/Misc.h>
//#include <Kernel/Scheduler.h>
//#include <Kernel/SpinTimer.h>
//#include <Kernel/Syscalls.h>
//#include <Kernel/VFS/FileIO.h>
//#include <Kernel/VFS/KBlockCache.h>
//#include <Kernel/VFS/KDriverDescriptor.h>
//#include <Kernel/VFS/KDriverManager.h>
//#include <Kernel/VFS/KDriverParametersBase.h>
//#include <Kernel/VFS/KFSVolume.h>
//#include <Kernel/VFS/KFileHandle.h>
//#include <Kernel/VFS/KFilesystem.h>
//#include <Kernel/VFS/KInode.h>
//#include <Kernel/VFS/KIOContext.h>
//#include <Kernel/VFS/KRootFilesystem.h>
//#include <Kernel/VFS/KVFSManager.h>
#include <Math/Acceleration.h>
#include <Math/Geometry.h>
#include <Math/LineSegment.h>
#include <Math/Misc.h>
#include <Math/PIDController.h>
#include <Math/Point.h>
#include <Math/Rect.h>
#include <Math/Vector.h>
#include <Ptr/NoPtr.h>
#include <Ptr/Ptr.h>
#include <Ptr/PtrTarget.h>
#include <RPC/ArgumentDeserializer.h>
#include <RPC/ArgumentPacker.h>
#include <RPC/ArgumentSerializer.h>
#include <RPC/RPCDefinition.h>
#include <RPC/RPCDispatcher.h>
#include <RPC/RPCInvoker.h>
#include <Signals/RemoteSignal.h>
#include <Signals/Signal.h>
#include <Signals/SignalTarget.h>
#include <Signals/SignalUnguarded.h>
#include <Signals/VFConnector.h>
#include <Storage/DirIterator.h>
#include <Storage/Directory.h>
#include <Storage/FSNode.h>
#include <Storage/File.h>
#include <Storage/FileReference.h>
#include <Storage/MemFile.h>
#include <Storage/NodeMonitor.h>
#include <Storage/Path.h>
#include <Storage/SeekableIO.h>
#include <Storage/StandardPaths.h>
#include <Storage/StreamableIO.h>
#include <Storage/Symlink.h>
#include <Storage/TempFile.h>
#include <System/ExceptionHandling.h>
#include <System/HandleObject.h>
#include <System/Platform.h>
#include <System/Sections.h>
#include <System/System.h>
#include <System/SystemMessageIDs.h>
#include <System/TimeValue.h>
#include <System/Types.h>
#include <Threads/ConditionVariable.h>
#include <Threads/EventHandler.h>
#include <Threads/EventTimer.h>
#include <Threads/Looper.h>
#include <Threads/Mutex.h>
#include <Threads/ObjectWaitGroup.h>
#include <Threads/Thread.h>
#include <Threads/Threads.h>
#include <Utils/Base64Codec.h>
#include <Utils/CircularBuffer.h>
#include <Utils/EasingCurve.h>
#include <Utils/EnumUtils.h>
#include <Utils/FactoryAutoRegistrator.h>
#include <Utils/HashCalculator.h>
#include <Utils/InertialScroller.h>
#include <Utils/IntrusiveList.h>
#include <Utils/JSON.h>
#include <Utils/Logging.h>
#include <Utils/MessagePort.h>
#include <Utils/String.h>
#include <Utils/TypeTraits.h>
#include <Utils/UTF8Utils.h>
#include <Utils/Utils.h>
#include <Utils/ValueAnimator.h>
#include <Utils/XMLFactory.h>
#include <Utils/XMLObjectParser.h>
#include <Utils/combsort.h>
#include <algorithm>
#include <array>
#include <assert.h>
#include <atomic>
#include <barrier>
//#include <bit>
//#include <bitset>
//#include <cassert>
//#include <cctype>
//#include <cerrno>
//#include <cfenv>
//#include <cfloat>
//#include <chrono>
//#include <clocale>
//#include <cmath>
//#include <codecvt>
//#include <compare>
//#include <complex>
//#include <condition_variable>
//#include <csignal>
//#include <cstdarg>
//#include <cstddef>
//#include <cstdint>
//#include <cstdio>
//#include <cstdlib>
//#include <cstring>
//#include <ctime>
//#include <ctype.h>
//#include <cwchar>
//#include <cwctype>
#include <deque>
//#include <devctl.h>
//#include <dirent.h>
//#include <errno.h>
#include <exception>
#include <experimental/scope>
//#include <fcntl.h>
//#include <filesystem>
//#include <float.h>
//#include <fmt/base.h>
//#include <fmt/chrono.h>
//#include <fmt/color.h>
//#include <fmt/compile.h>
//#include <fmt/core.h>
#include <fmt/format.h>
//#include <fmt/os.h>
//#include <fmt/ostream.h>
//#include <fmt/ranges.h>
//#include <fmt/std.h>
//#include <fmt/xchar.h>
#include <format>
//#include <forward_list>
//#include <fstream>
#include <functional>
//#include <future>
//#include <gtest/gtest.h>
#include <initializer_list>
//#include <inttypes.h>
//#include <ios>
//#include <iostream>
//#include <istream>
#include <iterator>
//#include <latch>
//#include <limits.h>
//#include <limits>
#include <list>
//#include <locale.h>
//#include <locale>
//#include <malloc.h>
#include <map>
//#include <math.h>
//#include <memory>
//#include <muParser.h>
//#include <muParserDef.h>
//#include <mutex>
//#include <new>
#include <nlohmann/json.hpp>
//#include <numeric>
//#include <optional>
//#include <ostream>
//#include <png.h>
//#include <print>
//#include <pthread.h>
//#include <pugixml.hpp>
#include <queue>
//#include <random>
#include <ranges>
//#include <ratio>
//#include <regex.h>
//#include <regex>
//#include <semaphore.h>
//#include <semaphore>
#include <set>
//#include <setjmp.h>
//#include <shared_mutex>
//#include <signal.h>
//#include <source_location>
//#include <span>
//#include <spawn.h>
//#include <sstream>
//#include <stack>
//#include <stdarg.h>
//#include <stdatomic.h>
//#include <stdbool.h>
#include <stddef.h>
#include <stdexcept>
#include <stdint.h>
#include <stdio.h>
//#include <stdlib.h>
//#include <stm32h7xx.h>
//#include <stop_token>
#include <string.h>
//#include <strings.h>
//#include <sys/cdefs.h>
//#include <sys/dirent.h>
//#include <sys/errno.h>
//#include <sys/fcntl.h>
//#include <sys/pados_error_codes.h>
//#include <sys/pados_mutex.h>
#include <sys/pados_syscalls.h>
//#include <sys/pados_threads.h>
//#include <sys/pados_types.h>
//#include <sys/param.h>
//#include <sys/resource.h>
//#include <sys/stat.h>
//#include <sys/syslimits.h>
//#include <sys/time.h>
//#include <sys/timeb.h>
//#include <sys/times.h>
//#include <sys/types.h>
//#include <sys/uio.h>
#include <sys/unistd.h>
//#include <sys/wait.h>
#include <system_error>
#include <thread>
//#include <time.h>
#include <tuple>
#include <type_traits>
//#include <typeindex>
#include <typeinfo>
#include <unistd.h>
//#include <unordered_map>
//#include <unordered_set>
#include <utility>
//#include <utime.h>
//#include <valarray>
//#include <variant>
#include <vector>
//#include <version>
//#include <zlib.h>
